### ISSUE TITLE
Mit mehreren Engines verbinden

### ISSUE THREAD

**Issue by roblen45** [atlas-engine-contrib/robotframework-processcube#11]
## Description

Es wäre praktisch, wenn man die in einem TestCase die ProcessCubeLibrary für mehrere Engines verwenden könnten.

Folgendes Szenario:

Ich möchte die MessageBus Extension testen. Dafür gibt es bereit ein Docker Setup mit 2 Engines. 
Auf der einen Engine werden Prozesse mit CatchEvents deployed, auf der anderen mit den entsprechenden Throw Events.
Dieses Setup funktioniert mit RabbitMQ, Mqtt und Azure ServiceBus.
Jetzt wäre es für den Test schön auf Engine 2 einen Prozess zu starten und auf Engine 1 zu überprüfen, ob der entsprechende Prozess mit dem CatchEvent über den Bus gestartet wurde.

**Comment by moellenbeck** [comment]
Es können mehrere Engine verwendet werden, wenn die jeweilige Engine mit Namen versehen werden:

```robotframework
Library           ProcessCubeLibrary    engine_url=http://%{ENGINE_1_HOST=localhost}:8000    WITH NAME    Engine1
Library           ProcessCubeLibrary    engine_url=http://%{ENGINE_1_HOST=localhost}:8001    WITH NAME    Engine2
```

Anschließend müssen die jeweiligen Keywords mit der entsprechenden Engine ausgeführt werden:

```robotframework
*** Tasks ***
Engine info from Engine01
    ${INFO}=    Engine01.Get Engine Info
    Log    ${INFO}


Engine info from Engine02
    ${INFO}=    Engine02.Get Engine Info
    Log    ${INFO}

```
